package reflectionandannotation.annotation;

import java.util.ArrayList;
import java.util.List;

/**
 * Exercise 2 & 3: Demonstrating Built-In Annotations (@Deprecated
 * and @SuppressWarnings)
 */

// Class demonstrating a legacy API transition
class LegacyAPI {

    // Mark the old feature as obsolete.
    // If you call this method, your IDE/Compiler will throw a warning indicating
    // deprecation.
    @Deprecated
    public void oldFeature() {
        System.out.println("Executing old feature... (Warning: It is deprecated and shouldn't be used)");
    }

    // Provide a modernized feature
    public void newFeature() {
        System.out.println("Executing a robust new feature. Use this over oldFeature()!");
    }
}

public class DeprecatedExercise {

    // Suppress rawtypes and unchecked warnings generated by the lack of List
    // generics
    @SuppressWarnings({ "unchecked", "rawtypes" })
    public static void main(String[] args) {
        System.out.println("--- Exercise 2: Using @Deprecated ---");
        LegacyAPI api = new LegacyAPI();

        // Emitting a warning but valid in execution
        api.oldFeature();

        // Recommended workflow
        api.newFeature();

        System.out.println("\n--- Exercise 3: Using @SuppressWarnings ---");
        // Creating an ArrayList lacking generics. Usually raises unchecked conversion
        // warnings.
        List rawList = new ArrayList();

        // Usually emits unchecked call warning
        rawList.add("Hidden Warning Context");
        rawList.add(2023);

        System.out.println("Successfully added varying data to non-generic List via warning suppression: " + rawList);
    }
}
